default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: /var/run/postgresql
  username: cho
  password:

development:
  <<: *default
  database: counter_development

test:
  <<: *default
  database: counter_test

production:
  <<: *default
  database: counter_production
  username: <%= ENV["COUNTER_DATABASE_USERNAME"] %>
  password: <%= ENV["COUNTER_DATABASE_PASSWORD"] %>
