default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV.fetch("POSTGRES_USER") { "cho" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>

development:
  <<: *default
  database: counter_development

test:
  <<: *default
  database: counter_test

production:
  <<: *default
  database: counter_production
  username: <%= ENV["COUNTER_DATABASE_USERNAME"] %>
  password: <%= ENV["COUNTER_DATABASE_PASSWORD"] %>
